import discord
from discord.ext import commands
import re
import random
import emoji
from datetime import datetime


class Shitposts(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self._last_member = None
        self.last_time_executed = datetime.utcfromtimestamp(0)
        self.last_message = None
        # there are four ways of setting up a post
        # 1: [regex]: """[post]""" # one keyword produces the one post
        # 2: [regex]: ("""[post], [image link]""") # one keyword produces one post w/ (embedded) image
        # 3: [regex]: ["""[post]""", """[post_cont]""" ... ] # a list of sentences for when one post is >2k chars
        # 4: [regex]: ["""[post]""", """[post_cont]""" ..., """random"""] # a list of posts to be chosen at random
        self.posts = {
            r"\bthe senate\b": (
                "**Did you ever hear the tragedy of Darth Plagueis the Wise? I thought not. It's not a story the Jedi would tell you. It's a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life... He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful... the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. Ironic, he could save others from death, but not himself.**",
                "https://imgur.com/8KPtRjS.png",
            ),
            r"\balpha\b": "I am the ultimate alpha male. I only climax for 1 of 2 reasons. I either climax for the purpose of reproduction with a beautiful woman (because that's the only kind of woman worthy of me) or I climax for the purpose of free protein. I need immense protein to maintain my ultimate alpha male body, and 4-5 cum loads a day is sufficient for me. It's not gay if it's mine, but I wouldn't expect you pathetic beta males to understand. I bet you waste your seed into napkins, tissue, and tube socks. How sad, wasting all that protein. Wasting all those offspring. Its optimal for me to masturbate with my legs over my head so I can practice stretching before my workout while I obtain my protein. All the gym betas in the locker room just look away in disgust, but again, I wouldn't be offended by an asshole who only focus on vanity muscles. You beta losers better start acting like real men.",
            r"^(based)+$": "Based? Based on what? In your dick? Please shut the fuck up and use words properly you fuckin troglodyte, do you think God gave us a freedom of speech just to spew random words that have no meaning that doesn't even correllate to the topic of the conversation? Like please you always complain about why no one talks to you or no one expresses their opinions on you because you're always spewing random shit like poggers based cringe and when you try to explain what it is and you just say that it's funny like what? What the fuck is funny about that do you think you'll just become a stand-up comedian that will get a standing ovation just because you said \"cum\" in the stage? HELL NO YOU FUCKIN IDIOT, so please shut the fuck up and use words properly you dumb bitch",
            r"\bmeow\b": """If you really want to be put on a leash and treated like a domestic animal then that’s called a fetish, not “quirky” or “cute”. What part of you seriously thinks that any part of acting like a feline establishes a reputation of appreciation? Is it your lack of any defining aspect of personality that urges you to resort to shitty representations of cats to create an illusion of meaning in your worthless life? Wearing “cat ears” in the shape of headbands further notes the complete absence of human attribution to your false sense of personality, such as intelligence or charisma in any form or shape. Where do you think this mindset’s gonna lead you? You think you’re funny, random, quirky even? What makes you think that acting like a fucking cat will make a goddamn hyena laugh? I, personally, feel extremely sympathetic towards you as your only escape from the worthless thing you call your existence is to pretend to be an animal. But it’s not a worthy choice to assert this horrifying fact as a dominant trait, mainly because personality traits require an initial personality to lay their foundation on. You’re not worthy of anybody’s time, so go fuck off, “cat-girl”.""",
            r"\bweed\b": """h-hewwo...owunce of weed pwease >///< arigato... dealer-kun puts weedie-chan in bong and inhales waaah!! (╯✧▽✧)╯ daisuki cannabis desu~! (^ ω ^ )uwaaa! weedie-chan i feel so kimochi!!(〃°ω°〃)""",
            r"(\bgamers?\b)(?!\sgirl)": [
                """You think you know human suffering? Try being a gamer. Us gamers are forced into the friendzone everyday by millions of women, all because we are not as built or as good looking as these stupid jocks and jerks. Well hey fuckheads, statistically, gamers last longer in bed, earn more money, and are way funnier! You people just don't like gamers because you fear us, because we have skills that most other people don't have. We have incredible communication skills, hand eye coordination, and other vital skills our ancestors used to fight in the wild, that has all been but washed away by our government and corporations so they could "do it for us". Gamers are on the rise, and there is no stopping us. We won't be silenced, and we won't be stopped. Just you wait. All the presidents now are playing golf, but soon, they will be playing Call of Duty and HALO. They will be into memes and even support Gang Weed, unlike the stupid pumpkin spice racist president we have now; I dare not mention his name. I'm so sick of it, and one day, after all the shit you've given us, after all the pain you have put us gamers through, you will be the ones under our control. But don't worry, we won't treat you nearly as bad as you treated us. Because we aren't monsters. We are gamers.""",
                """Gaming IS an exercise, period. Its one of the very few activities that require both constant muscle and mind activity. Split-second reactions, mechanical accuracy, mind bending puzzles. Handling a keyboard and a mouse for HOURS. This is all nothing for gamers. Its our second nature.\nPlease take a step back and consider your actions before going around defaming gamers like that.""",
                """random""",
            ],
            r"\bbourgeoisie\b|\bbourgeois\b": [
                """Folks, the bourgeois, they're no good, more and more people are saying it. All these workers— the biggest, we have the biggest workers— very handsome workers come up to me and say, Comrade Trump there is a specter haunting Europe, and you know what, they're right. These bourgeois are very nasty people, very very rude, and very unfair to the workers. They are stealing our surplus value and no one is doing anything about it. The proletariat comes up to me every day and says, Comrade Trump will you lead the revolution? And I gotta turn to them and say look, the instruments of capitalism will be used to bring about its destruction, believe me. The means of production, Obama never wanted to seize them. Well guess what? I'm seizing them. Landlords? They're done for folks. Everyone told me— they said, Comrade Trump you won't be the vanguard of the revolution and they would laugh, the media laughed the democrats laughed, guess who's laughing now?""",
                """And then you have these capitalists, those are real beauties! This is their new hoax- they take a piece of machine, a big beautiful shiny new means of production, and they buy it and y'know, they own it, it's a big beautiful shiny new machine, all the bells and whistles, bing bing bing, and then they have the workers- who are totally not being treated fairly in this country, folks, BELIEVE ME, totally exploited, and they have these workers-and they pay them a certain amount, could beee... $20 per hour, could be TEN, could be FIVE, could be TWELVE, they pay them a certain amount, okay, and with their labor they build the product.""",
                """And the owner of the machine, of the capital, "Capitalist" they turn around and sell the product at a yuge markup, they call it "profit." ok, so they call it profit! They don't sell it at the cost it took to make it, okay, so what do they do with this extra, you know what I call it? I call it surplus value. I call it surplus value, and do they share the surplus value with the people whose labor PROVIDED the value it took to make that product? I don't think so, folks.""",
                """They stick in a bank and then they say "ohhhh I can't afford to pay you more!" Bad- BAD people. It's totally phony, folks. Raw deal, our proletariat are getting a raw deal. But not for long! We're gonna- and by the way it never occurs the workers to pool their resources and buy the big beautiful machine in order to share the profit that they created in the first place with their labour! And you know why? Because the capitalists pay the workers such a low wage they can't afford to then invest and pool their money and share in ownership... of the means of production! Can't do it! This is the biggest scam on the planet, folks! Boy, I've heard some real beauties but that one, WOW, that's a doozy. That's a real beauty. But we're gonna fix it, folks, we're gonna fix it, okay? and you know what the laborers are going to do? They're gonna WIN.""",
                """Folks, what we did in 1917–the Revolution I call it, with a capital R–it's never been done before. So many big beautiful red flags, you couldn't even–now that, folks, that's a flag we stand up for, we don't kneel for our terrific red flag–and you couldn't even see the Winter Palace, you know. You know the Mensheviks, you take a look at what they said, and they were a, uh, a failed party, and Renegade Kautsky, very nasty to me but that's okay, they said we couldn't do it! They said, "Oh, Vlad, the material conditions are bad, we have to have a bourgeois republic to develop the forces of production." You know what that means, right? Semi-feudal economy! Okay, you get Semi-Feudal, and I said, I told them we can't have Semi-Feudal. Well, look at where we are now, Julius. We are going to develop the forces of production so fast it'll make your head spin. We are going to do in a generation what it took them many, many years to do. BELIEVE ME.""",
            ],
            r"\blegos\b": """You know it isn't "Legos". You've had FUCKING YEARS to adjust to the actual, correct way to say the term. It's Lego. Lego bricks, Lego sets, Lego kits, Lego mini-figures, Lego City. There are no such things as "Legos". They don't exist. "Lego" refers to the COMPANY THAT MAKES THE TOY, and thus the shortening Lego is acceptable. Saying "I'm playing with my Lego" works because it's referring to the sets themselves: The individuals aspects that make of the toy from the bricks to the mini-figures to the electronics to the other little parts. It isn't claiming that the fucking square bricks are each a Lego. THE ENTIRE THING IS. If you were to say "I'm playing with my Legos" that implies that you're playing with at least two different types of Lego set at once, i.e. Lego City and Bionicle. Still saying LEGOS after all these years makes you look like an assclown. Here in Europe, the continent responsible for this toy (no, it wasn't made by America, no matter how much your capitalistic toy industry wants you to think), you'd be laughed out of the room if you said that.""",
            r"\bgrilled cheese\b": [
                """A grilled cheese consists of only these following items. Cheese. Bread with spread (usually butter). This entire subreddit consist of "melts". Almost every "grilled cheese" sandwich i see on here has other items added to it. The fact that this subreddit is called "grilledcheese" is nothing short of utter blasphemy. Let me start out by saying I have nothing against melts, I just hate their association with sandwiches that are not grilled cheeses. Adding cheese to your tuna sandwich? It's called a Tuna melt. Totally different. Want to add bacon and some pretentious bread crumbs with spinach? I don't know what the hell you'd call that but it's not a grilled cheese. I would be more than willing to wager I've eaten more grilled cheeses in my 21 years than any of you had in your entire lives. I have one almost everyday and sometimes more than just one sandwich. Want to personalize your grilled cheese? Use a mix of different cheeses or use sourdough or french bread.""",
                """But if you want to add some pulled pork and take a picture of it, make your own subreddit entitled "melts" because that is not a fucking grilled cheese. I'm not a religious man nor am I anything close to a culinary expert. But as a bland white mid-western male I am honestly the most passionate person when it comes to grilled cheese and mac & cheese. All of you foodies stay the hell away from our grilled cheeses and stop associating your sandwich melts with them. Yet again, it is utter blasphemy and it rocks me to the core of my pale being. Shit, I stopped lurking after 3 years and made this account for the sole purpose of posting this. I've seen post after post of peoples "grilled cheeses" all over reddit and it's been driving me insane. The moment i saw this subreddit this morning I finally snapped. Hell, I may even start my own subreddit just because I know this one exists now. You god damn heretics. Respect the grilled cheese and stop changing it into whatever you like and love it for it what it is. Or make your damn melt sandwich and call it for what it is. A melt.""",
            ],
            r"\bepstein\b": "JOSH: Drake... where's Epstein?\nDRAKE: He’s right in there. See, I put him on suicide watch.\n[laugh track]\nJOSH: You were supposed to monitor him constantly.\nDRAKE: Dude, I'm gonna!\nJOSH: Oh really?\nDRAKE: Yes!\nJOSH: So go check on him!\nDRAKE: Okay, I will! tcch\n[laugh track]\n[rattles the door, peeps through the door, turns around]\nDRAKE: ...I see the problem.\nJOSH: Oh do ya?",
            r"\bdrugs\b": """We should not be arrested for drugs if we are just vibing. If we are just vibing, it's our vibe, drugs a vibe so we should be able to vibe, it's part of our identity""",
            r"\bparis\b|\bvenice\b": """You know Paris? In English, it's pronounced "Paris" but everyone else pronounces it without the "s" sound, like the French do. But with Venezia, everyone pronouces it the English way – "Venice". Like The Merchant of Venice or Death in Venice. WHY, THOUGH!? WHY ISN'T THE TITLE DEATH IN VENEZIA!? ARE YOU FUCKING KIDDING ME!? IT TAKES PLACE IN ITALY, SO USE THE ITALIAN WORD, DAMMIT! THAT SHIT PISSES ME OFF! BUNCH OF DUMBASSES!"""
            r"\battack\shelicopter\b|\bsexually\sidentify\b"
            """I sexually Identify as the "I sexually identify as an attack helicopter" joke. Ever since I was a child, I've dreamed of flippantly dismissing any concepts or discussions regarding gender that don't fit in with what I learned in 8th grade bio. People say to me that this joke hasn't been funny since 2014 and please at least come up with a new one, but I don't care, I'm hilarious. I'm having a plastic surgeon install Ctrl, C, and V keys on my body. From now on I want you guys to call me "epic kek dank meme tr***ies owned with facts and logic" and respect my right to shit up social media. If you can't accept me you're a memeophobe and need to check your ability-to-critically-think privilege. Thank you for being so understanding.""",
            r"\bkfc\b": """One time I was asked if I was a legs man or a breasts man, I said I was into shaved pussy and anal and now I’m “banned from KFC” and “a possible sex offender”""",
            r"\bcat\b": """cat""",
            r"\blolis?\b|\blolicons?\b": [
                """1. A fetish does not make you a creep. For instance, people can be turned on by incest porn, but not want to fuck their own sister. Furries don't often want to fuck animals. And PLENTY of people like porn that involves cheating or rape, but would NEVER do those. Just so, loli fans aren't just a bunch of pedos (though statistically maybe a few probably are, but you could say that about any fetish). For instance, I'm a loli fan myself, but I have an 8 year old daughter who regularly brings friends over, and not ONCE (I swear) have I seen a single one of them in a sexual light. I'm attracted to the cute designs and innocent attitudes of lolis, that doesn't mean I'm gonna go fuck children, that's obviously fucking disgusting. Not to mention, most lolis are legal, it's the design, NOT the age that makes a loli.?""",
                """2. Anime style video games, and games from Japan always have the "cute" option when picking love interests. Usually some young, innocent girl with a shy attitude. And yes, I'm well aware Futaba kinda falls in that category too, but she can also fall under the "geeky girl" concept, which is also typically a separate option from the "cute" one. And since the twins are explained multiple times to be much older, that really does just make them cute, and nothing more. It's a very normal thing for a game like this to make them dateable.""",
                """3. THEY'RE FUCKING VIRTUAL. At the end of the day, if my first two points didn't make you feel stupid, this one should. If you can't accept that people can have a fetish without becoming a creep, or that these are normal, long time tropes in Japanese games, then at least accept the fact that there's no point attacking people for wanting VIRTUAL CHARACTERS to be dateable. After all, who the hell is that hurting? Sure as hell not any kids, that's for sure. So why even bother getting pissy? What, cuz YOU don't wanna date em? Then don't! Simple as that!""",
            ],
            r"\bamerica\b|\bamerika\b|\bunited\sstates\b": """death to amerika""",
            r"\bdprk\b|\bnorth\skorea\b": """juche gang juche gang juche gang""",
            r"\bussr\b": """> ussr\n19 August 1991 worst day of my life""",
            r"\brawr\b|\bxd\b": """x3 nuzzles how are you pounces on you you're so warm o3o notices you have a bulge o: someone's happy ;) nuzzles your necky wecky~ murr~ hehehe rubbies your bulgy wolgy you're so big :oooo rubbies more on your bulgy wolgy it doesn't stop growing ·///· kisses you and lickies your necky daddy likies (; nuzzles wuzzles I hope daddy really likes $: wiggles butt and squirms I want to see your big daddy meat~ wiggles butt I have a little itch o3o wags tail can you please get my itch~ puts paws on your chest nyea~ its a seven inch itch rubs your chest can you help me pwease squirms pwetty pwease sad face I need to be punished runs paws down your chest and bites lip like I need to be punished really good~ paws on your bulge as I lick my lips I'm getting thirsty. I can go for some milk unbuttons your pants as my eyes glow you smell so musky :v licks shaft mmmm~ so musky drools all over your cock your daddy meat I like fondles Mr. Fuzzy Balls hehe puts snout on balls and inhales deeply oh god im so hard~ licks balls punish me daddy~ nyea~ squirms more and wiggles butt I love your musky goodness bites lip please punish me licks lips nyea~ suckles on your tip so good licks pre of your cock salty goodness~ eyes role back and goes balls deep mmmm~ moans and suckles""",
            r"\bdad\b": """> dad\ndaddy*""",
            r"\bairsoft\b": """Airsoft is so fucking dumb. Oh you think you’re cool because you play with toy guns? Go fuck yourself. No, you’re not a Navy SEAL: you’re a pathetic excuse for an American cosplaying as one, you piece of shit. What’s that? You have the audacity to call airsoft a sport? Fuck you. It’s a past time for sweaty little nerds who fantasize war. Show some fucking respect and grow a pair of balls by enlisting, you fat fuck. Oh you modified your airsoft gun? Cool. I couldn’t give any less of a fuck. I don’t really care what my gun looks like when I’m fighting for my god damn life in Afghanistan. Next time you’re at the arena I hope you consider how truly fucking stupid of a hobby airsoft really is.""",
            r"\bcracker\b|\bcracka\b": """Please, they are very fragile, call them Porcelain Americans instead.""",
            r"\bvolcel\spolice\b": (
                """The VOLCEL POLICE are on the scene! PLEASE KEEP YOUR VITAL ESSENCES TO YOURSELVES AT ALL TIMES.\nنحن شرطة VolCel. بناءا على تعليمات الهيئة لترويج لألعاب الفيديو و النهي عن الجنس نرجوا الإبتعاد عن أي أفكار جنسية و الحفاظ على حيواناتكم المنويَّة حتى يوم الحساب. اتقوا الله، إنك لا تراه لكنه يراك.""",
                """https://i.imgur.com/P5UMuVz.jpg""",
            ),
            r"\bisrael\b": """"Get the fuck out of my phone," I scream, smashing it against a passing Arab child. The girl tries to apologize to me for breaking my phone with her skull, but it is too late. The sound of a .308 round hitting her chest lets me know that the threat has been neutralized. A week later, I am informed that her family has refused to compensate me for the loss of my phone, and thus I am now the legal owner of a 2.7 acre olive grove outside of Hebron. The state has provided me with a CAT D6 to assist with the move-in.""",
            r"\bboth sides\b": """> both sides\nIn this moment I am euphoric""",
            r"\bboomers?\b": [
                """Any boomer born before 1964 can't cook. All they know is Remember Benghazi, don't tip, say N-Word, general confusion, and fucking die""",
                """Probably never even held a gun before. Sitting in the bathroom yankin off to cartoon porn. I've lived a real life and you snowflakes and your damned bitch asses don't even know what bathroom to use. 57 fucking genders, your generation is useless and weak. Pathetic liberals wanting everything to be free. Your kind makes me vomit in disgust. Each day I beg for a "triggered" bitch to approach me. Yet none will. I hope someday I can beat a libtard like you into the ground. Man the thought makes me feel soooooo happy! Yet not one has come to me even though I wear mega hats and shirt's. But you little gay ass boys only attack women and the elderly, because you haven't the balls to go after a man. Pathetic ass useless generation. Your mother should have shot you! Daddy should have beat the queer out of you! Drink some bleach and STFU!""",
                """Do yourself a favor and delete your social media account. Because l've doxed you and have published your account information, your comments as well as your private information on Reddit. I've done this for posterity purposes. ROFLMAO. Also cancel culture works both ways. How does it look for you that you're making fun of geriatrics? Not that I am one, I just find it hilarious that your future is over at this point. When potential employers look you up, they're gonna find out that you're a bully who picks on the elderly.""",
                """ILL SAY THIS FOR EVERYONE MY AGE, ESPECIALLY MILLIANIALS THAT DONT KNOW SHIT ABOUT REAL CARS. WE MISS THE DAYS OF OLDSMOBILE, PONTIAC WERE ON TOP OF THEIR GAME.ENGINES WERE BIGGER, MORE RELIABLE. YOU HAD NO REPLACEMENT FOR DISPLACEMENT. YOU DIDNT HAVE A BELL GOING OFF IN YOUR TO TELL YOU TO PUT YOUR SEATBELT ON. YOU DIDNT NEED AIR CONDITIONING, OR A MILLION BUTTONS FOR A RADIO. DIDNT NEED NO FANCY DIGITAL DISPLAYS. GAUGES WERE ANALOG AND WORKED FINE. I MISS CARS WERE 15 FT LONG OFCHROME BUMPERS, WOODGRAIN, STEEL, AND RAW SEX APPEAL. NOW ITS PLASTIC AND EVERYTHING LOOKS THE SAME, CARS DONT HAVE CHARACTER ANYMORE. THEY USED TO BE PIECES OF ART NOW THEYRE JUST PRESSED AND STAMPED REPEATEDLY OVER AND OVER.\n- Ernie""",
                """I’m sick and tired of you kids making fun of boomers. Do you realize you probably wouldn’t exist without boomers? You’d probably be cum in a sock or swallowed by some whore at a truck stop if wasn’t for your dad, who is a boomer. Boomers are awesome they made the world it is today. Thanks to them the planet is getting warmer so we get to spend more time at the beach, they’ve made the planet a better place for us and we should be grateful. Stop hating on boomers it makes you look like the spoiled brat that you are. Boomers created spongebob and rick and morty and all the gay cartoons you love. Maybe you should watch more boomer shows and stfu you little bitch. Guess what? Joker was played by a boomer dumbass so why so serious??? Shut up millennial!! Why don’t you go jack off on Snapchat to some e thot or make a fool of yourself on tik Tok for the world to remember you as a waste of breath??! Shut up boomer?!!?! How about you attach some breast pumps to your huge man boobs and make some breast milk cheese to sell in the local farmers market because what else are you good for you young sapling!!! Saying shut up boomer isn’t funny!!! You shut up!!! Idiot""",
                """At this point there's no excuse for baby boomers still in the workforce to be technologically inept anymore It's just willful ignorance, this shit is not fucking hard "Why is it asking for a password?", Because you're logging into something, Martha. That's how it's been for the last 20 fucking years. "How do I do this, Can you show me?" No, Jeb, you can Google it like the rest of us. You've been an engineer and working with computers for 35 years. Why would I waste time when some 12 year old indian kid on youtube can walk you through it far more clearly? It requires one exposure to the concept of googling to understand how it work Your generation was smart enough to create a giant hole in the ozone, but not smart enough to realize you have the near entirety of human knowledge at your disposal just by typing in a few words? Give me a break "I'm not tech savvy", No, you just refuse to learn despite most modern software being idiot proof, stuck in your ways out of entitlement.\n\nAND ANOTHER THING that just gets my blood boiling is their ability to get into their settings, completely fuck things up, and then manage to develop total amnesia about how it happened. What do you mean you set your phone to Japanese on accident Deborah? There's like 15 separate menus you have to navigate through to get there. "I think it's because l got a virus". No, Arthur, it's not a virus, the only viruses here are your rampant stupidity and the deadly pathogens carried by your unvaccinated and probably ugly grandchildren. I just absolutely loathe that the people who decide if women should be executed for having abortions or not are the same people who can't figure out how to work a blu-ray player with the instructions right in front of them.""",
                """These stupid fucking kids think they are smart saying all these shit huh?! Let me tell you something kid I was drafted in 1966 to the Vietnam War there I grew up in the battlefield to be a cold hearted murderer nothing can stop me there, especially the Vietnamese. I murdered them all like flies I was a hungry soldier there so listen up shit pig if you think that you can disrespect me by calling me fucking boomer or some shit I'm gonna plow you down knock you up karate chop you and straight up slam your pathetic snowflake body which will cause you to melt and whine like the millenials snowflakes that you are. You kids thinks it's funny to call us old folks boomer huh just because we are old dumb and docile well kid this old man has seen hell and has got back from it, this old man has gone through the presidency of Ricard Nixon and last of all this old man has teeth that can still bite you mean. So next time you call someone a boomer watchout kiddo they might just be your demise, now go back to listening to modern rap crap garbage and identifying yourself as another gender stupid fucking millenials all they do is whine and play their phone can't they just go out?.""",
                """I'm 50, SNOWFLAKE. I own 5 companies in Texas and make a shitload of money. I pay taxes, workout, bang my wife an animal, have healthy relationships and basically live like a ROCKSTAR without having to get on stage. I have the intelligence to look at both sides of an argument and figure out the real facts. Meanwhile, you are an average income (basically broke) "reporter" (fake news) who blames people like me for your problems and shortcomings. Bottom line is that your parents spoiled your ass and you think you know it all. If you were my son I would slap the shit out of you.""",
                """I am a so called “boomer” and I do not appreciate you disgusting millenials calling me this hate word. You have no right, I am the only reason you idiots are here today. You have no right to insult me. Let me look at my minions jokes in peace you idiotic creatures.""",
                """Every downvote here is a clear indication that you're fine with prejudice. It shows that you have absolutely no problems making gross assumptions about an entire group of people based on a couple of individuals or based on assumptions or based on currently popular memes. It shows that you're more than happy to treat an entire group of people with disdain, because it's so much easier to blame someone else for your issues. If this was a group classified by race, sex, or gender identity, you'd all be jumping to march for old-people-matter! So, 'boomers' get blamed for your inability to buy a house, even though your aspirations are to work McDonalds and surf all day and you have to have the latest most expensive toys (i.e. iphones, new trucks, etc). We get blamed for spreading Covid as if we're the ones throwing the raves and partying in the bars all night. Like I said, it's always so easy to blame someone else. Keep it up. One of these day, if/when you grow up, you'll learn. Until then, please, continue to blame everyone else for your own issues, 'cause, you know, that always solves the issues.""",
                """random""",
            ],
            r"\bkaren\b": """I'm surprised that "Karen" isn't a more popular porn category. Like, there's so much potential.\nKaren: "Excuse me, but do you have this milk in a different size? I need 2 liters, but you guys only have 1 liter!"\nGuy who looks really young, but trust me, he's an adult: "Umm... I'm not so sure, I'll have to check in the back."\nKaren: "Ugh, hurry up then."\n*Guy goes in the back to look for the milk, but instead of looking for the milk, he peeks out the door to get short glimpses of Karen's milk jugs*\n*Guy starts touching himself, eventually unzipping his pants to start stroking his meat*\n*Camera pans to Karen's body, occasionally zooming in on Guy's face and pp, because fuck you*\nKaren, after busting through the door: "UHH HELLO? WHY ARE YOU TAKING SO LONG!?!?"\nGuy, quickly grabbing a bag of frozen chicken nuggets to cover his junk: "Uhh ummm nothing! I'm just looking for your milk!"\nKaren, while grabbing the back of nuggets: "THAT'S NOT MILK, THESE ARE NUGGETS YOU DUMBASS"\n*The guy does a death grip on the bag, desperately trying to hide his junk*\n*Karen pulls it hard enough to break the guy's grip, exposing his hard cock*\n*Karen does that trademark Brazzers shocked face. You know, the one everyone makes on PornHub ads. You know what the fuck I'm talking about*\nKaren: "What the fuck???"\nThe guy: "No no no, it's not what it looks like! Please don't call my manager!"\n*Karen walks away, but slips, and the guys penis magically slips inside of her*\n*They start fucking*\n*The porn ends with the manager walking in and saying "What the fuck???"*""",
            r"(\bgamer\sgirls?\b)|(\bgirl\sgamers?\b)": [
                """So the other day, I was playing rainbow six siege, and I heard one of my teammates make a callout in the voice chat. It was a real life gamer girl. God, I kid you not, I just stopped playing and pulled my dick out. “fuck, Fuck!” I was yelling in voice chat. I just wanted to hear her voice again. “Please,” I moaned. But she left the lobby. I was crying and covered in my own cum, but I remembered that I could find recent teammates in the ubiplay friends tab. I frantically closed down siege and opened the tab, to find out she had TTV IN HER NAME!!! She was streaming, and only had 100 viewers!!! The competition was low, so I made the first move and donated my months rent to her. I was already about to pre. She read my donation in the chat. God this is the happiest I’ve been in a long time. I did a little research, and found out where she goes to school, but I am a little nervous to talk to her in person, and need support. Any advice before my Uber gets to her middle school?""",
                """A girl.... AND a gamer? Whoa mama! Hummina hummina hummina bazooooooooing! eyes pop out AROOOOOOOOGA! jaw drops tongue rolls out WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF WOOF tongue bursts out of the outh uncontrollably leaking face and everything in reach WURBLWUBRLBWURblrwurblwurlbrwubrlwburlwbruwrlblwublr tiny cupid shoots an arrow through heart Ahhhhhhhhhhh me lady... heart in the shape of a heart starts beating so hard you can see it through shirt ba-bum ba-bum ba-bum ba-bum ba-bum milk truck crashes into a bakery store in the background spiling white liquid and dough on the streets BABY WANTS TO FUCK inhales from the gas tank honka honka honka honka masturabtes furiously ohhhh my gooooodd~""",
                """random""",
            ],
            r"\bsnowflake\b": """did I OFFEND you? Do you want a bandaid? Do you want a hug? Do you want a kiss? I will kiss you. I will do it. Right on the mouth. Come here snowflake.. that's it.. your lips are so soft, snowflake.. mnnhm... ah...... snowflake..........""",
            r"\bpc\sculture\b": [
                """i went to starbucks and the cashier guy said “Would you like a BLACK coffee” and i said no and he said “YOU DONT LIKE BLACK? RACIST” and slammed a brick into my head, knocking me out. when i woke up i was in the cashier’s basement at his house, strapped to a giant machine along with other people who have declined the black coffee, i have been watching as the machine harvests 1 organ from each person and appears to be constructing a new person out of our collective organs. the cashier is walking around a catwalk screaming at us about how he is impotent but desperately wants to be a father and how he will use our worthless racist organs to still create a child through science, and he will teach it to be kind and accepting instead of a bigot. it looks like i am next to have one of my organs ripped out. ladies and gentlemen, PC culture has gone too far :/""",
                """I'M SEETHING WITH RAGE 🤬🤬🤬 THIS IS ❌UNACCEPTABLE❌ HANS CHRISTIAN ANDERSEN DIDN'T DIE FOR THIS ☠️ IT SAYS EXPLICITLY IN THE LITTLE MERMAID LORE THAT ARIEL HAS TO BE WHITE 👩🏻‍🦰 SO THAT ONLY OUR PRECIOUS WHITE CHILDREN 👩🏻 CAN IDENTIFY WITH A RETARDED HALF FISH 🐟👩🏻‍🦰 WHO DOESN'T KNOW HOW TO USE A FORK 🍴 SMH 😫 PC CULTURE HAS DONE DID IT NOW 😾 SOON THE GAYS 🌈 AND BLACKS 🎅🏿 WILL TAKE OVER\nI guess you could say 👈👆 the script will be written 👉👇 in Ariel Black 😎""",
                """random""",
            ],
            r"\bslippery\sslopes?\b": """> slippery slope\nshut the fuck up""",
            r"\bsneeze\b": """😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😩😳🤧 scuse me""",
            r"(\bcock and ball torture\b)|(\bcbt\b)": """Cock and ball torture (CBT), penis torture or dick torture is a sexual activity involving application of pain or constriction to the penis or testicles. This may involve directly painful activities, such as genital piercing, wax play, genital spanking, squeezing, ball-busting, genital flogging, urethral play, tickle torture, erotic electrostimulation, kneeing or kicking. The recipient of such activities may receive direct physical pleasure via masochism, or emotional pleasure through erotic humiliation, or knowledge that the play is pleasing to a sadistic dominant. Many of these practices carry significant health risks.""",
            r"(\blibertarians?\b)|(\blibertarianism\b)|(\bancaps?\b)": [
                """I was shooting heroin and reading “The Fountainhead” in the front seat of my privately owned police cruiser when a call came in. I put a quarter in the radio to activate it. It was the chief.\n"Bad news, detective. We got a situation.”\n“What? Is the mayor trying to ban trans fats again?”\n“Worse. Somebody just stole four hundred and forty-seven million dollars’ worth of bitcoins.”\nThe heroin needle practically fell out of my arm. “What kind of monster would do something like that? Bitcoins are the ultimate currency: virtual, anonymous, stateless. They represent true economic freedom, not subject to arbitrary manipulation by any government. Do we have any leads?”\n“Not yet. But mark my words: we’re going to figure out who did this and we’re going to take them down … provided someone pays us a fair market rate to do so.”\n“Easy, chief,” I said. “Any rate the market offers is, by definition, fair.”\nHe laughed. “That’s why you’re the best I got, Lisowski. Now you get out there and find those bitcoins.”\n“Don’t worry,” I said. “I’m on it.”\nI put a quarter in the siren. Ten minutes later, I was on the scene. It was a normal office building, strangled on all sides by public sidewalks. I hopped over them and went inside.\n“Home Depot™ Presents the Police!®” I said, flashing my badge and my gun and a small picture of Ron Paul. “Nobody move unless you want to!” They didn’t.\n“Now, which one of you punks is going to pay me to investigate this crime?” No one spoke up.\n“Come on,” I said. “Don’t you all understand that the protection of private property is the foundation of all personal liberty?”\nIt didn’t seem like they did.\n“Seriously, guys. Without a strong economic motivator, I’m just going to stand here and not solve this case. Cash is fine, but I prefer being paid in gold bullion or autographed Penn Jillette posters.”\nNothing. These people were stonewalling me. It almost seemed like they didn’t care that a fortune in computer money invented to buy drugs was missing.""",
                """I figured I could wait them out. I lit several cigarettes indoors. A pregnant lady coughed, and I told her that secondhand smoke is a myth. Just then, a man in glasses made a break for it.\n“Subway™ Eat Fresh and Freeze, Scumbag!®” I yelled.\nToo late. He was already out the front door. I went after him.\n“Stop right there!” I yelled as I ran. He was faster than me because I always try to avoid stepping on public sidewalks. Our country needs a private-sidewalk voucher system, but, thanks to the incestuous interplay between our corrupt federal government and the public-sidewalk lobby, it will never happen.\nI was losing him. “Listen, I’ll pay you to stop!” I yelled. “What would you consider an appropriate price point for stopping? I’ll offer you a thirteenth of an ounce of gold and a gently worn ‘Bob Barr ‘08’ extra-large long-sleeved men’s T-shirt!”\nHe turned. In his hand was a revolver that the Constitution said he had every right to own. He fired at me and missed. I pulled my own gun, put a quarter in it, and fired back. The bullet lodged in a U.S.P.S. mailbox less than a foot from his head. I shot the mailbox again, on purpose.\n“All right, all right!” the man yelled, throwing down his weapon. “I give up, cop! I confess: I took the bitcoins.”\n“Why’d you do it?” I asked, as I slapped a pair of Oikos™ Greek Yogurt Presents Handcuffs® on the guy.\n“Because I was afraid.”\n“Afraid?”\n“Afraid of an economic future free from the pernicious meddling of central bankers,” he said. “I’m a central banker.”\nI wanted to coldcock the guy. Years ago, a central banker killed my partner. Instead, I shook my head.\n“Let this be a message to all your central-banker friends out on the street,” I said. “No matter how many bitcoins you steal, you’ll never take away the dream of an open society based on the principles of personal and economic freedom.”\nHe nodded, because he knew I was right. Then he swiped his credit card to pay me for arresting him.""",
            ],
        }

    @commands.Cog.listener()
    async def on_message(self, message):
        if message.author == self.bot.user:
            return None
        # there's two checks to prevent message spam: if it's been a minute since the last message
        # AND that it isn't doing the same reply twice in a row
        time_dif = (datetime.utcnow() - self.last_time_executed).total_seconds()
        for key in self.posts:
            val = self.posts.get(key)
            link = None
            match = re.search(key, message.content.lower())
            if match and match.group(0) != self.last_message and time_dif >= 60:
                # update spam conditions after match is found
                self.last_message = match.group(0)
                self.last_time_executed = datetime.utcnow()
                output = val
                if isinstance(output, tuple):
                    link = output[1]
                if link is not None:
                    picture = discord.Embed()
                    picture.set_image(url=link)
                    await message.channel.send(content=output[0], embed=picture)
                elif isinstance(output, list):
                    if output[-1] == "random":
                        await message.channel.send(random.choice(output[:-1]))
                    else:
                        for line in output:
                            await message.channel.send(line)
                else:
                    await message.channel.send(output)


def setup(bot):
    bot.add_cog(Shitposts(bot))
